language: node_js
sudo: false
node_js:
- '9'

branches:
  only:
  - fish

deploy:
  provider: heroku
  api_key:
    secure: c7195355-2516-48de-993a-82e61097c074
  app: test-dev-server
  on:
    repo: tarados-feroces/frontend
    branch: fish
  skip_cleanup: true

before_script:
  - npm install
