language: node_js
sudo: false
node_js:
- '9'

branches:
  only:
  - master

deploy:
  provider: heroku
  api_key:
    secure: $MASTER_KEY
  app: tf-master-server
  on:
    repo: tarados-feroces/frontend
    branch: master
  skip_cleanup: true

before_script:
  - npm install
